CREATE DEFINER=`root`@`localhost` FUNCTION `GET_RANDOM_SELLER_REGISTRATION`() RETURNS varchar(5) CHARSET utf8mb4
BEGIN
DECLARE COUNT_SELLERS INT;
DECLARE RANDOM_SELLER INT;

SELECT COUNT(*) INTO COUNT_SELLERS FROM vendedores;
SET RANDOM_SELLER = (SELECT RANDOM_NUMBER(1, COUNT_SELLERS)) - 1;
RETURN (SELECT MATRICULA FROM vendedores LIMIT RANDOM_SELLER, 1);
END